---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buyerservice
    spec:
      containers:
      - name: buyerservice
        image: pbehague/buyerservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3011
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: http://*:3011
          - name: ConnectionStrings__sqlestateagentdata
            value: "Server=sqlestateagentbuyerdata;Database=EABuyer;User Id=sa;Password=PaSSw0rdPaSSw0rd;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True"
  selector:
    matchLabels:
      app: buyerservice

---
apiVersion: v1
kind: Service
metadata:
  name: buyerservice
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3011
    targetPort: 3011
    nodePort: 32011
  selector:
    app: buyerservice